// SPDX-License-Identifier: MIT
// Copyright (c) 2019 Ha Thach (tinyusb.org)
// Copyright (c) 2023 Rene Wolf
// Copyright (c) 2025 Jitterbug

#ifndef _USB_DESCRIPTORS_H
#define _USB_DESCRIPTORS_H

#include <stdint.h>

// Input terminal (line input)
#define USB_DESCRIPTORS_ID_INPUT_PCM1802 0x01
// The switch to select debug output or normal audio output
#define USB_DESCRIPTORS_ID_FEATURE_AUDIO 0x03
// Output terminal (USB)
#define USB_DESCRIPTORS_ID_OUTPUT        0x04
// Clock Source units
#define USB_DESCRIPTORS_ID_CLOCK         0x05

// Fake signal path units
#define USB_DESCRIPTORS_ID_INPUT_20      0x10
#define USB_DESCRIPTORS_ID_INPUT_28      0x11
#define USB_DESCRIPTORS_ID_INPUT_40      0x12
#define USB_DESCRIPTORS_ID_INPUT_50      0x13

#define USB_DESCRIPTORS_ID_SELECT_CLK0   0x20
#define USB_DESCRIPTORS_ID_SELECT_CLK1   0x21

#define USB_DESCRIPTORS_ID_OUTPUT_CLK0   0x30
#define USB_DESCRIPTORS_ID_OUTPUT_CLK1   0x31


#define USB_DESCRIPTOR_SERIAL_LEN 16
void usb_descriptor_set_serial(const char* serial);

const uint16_t* usb_descriptor_get_strd_idx_input_freqs(uint8_t* len);
const uint8_t* usb_descriptor_get_ms_os_20(uint8_t* len);

/* 4.7.2.7 Selector Unit Descriptor */
#define TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN (7+4)
#define TUD_AUDIO_DESC_SELECTOR_UNIT_4(_bUnitID, _baSourceID1, _baSourceID2, _baSourceID3, _baSourceID4, _bmControls, _iSelector) \
	TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN, \
	TUSB_DESC_CS_INTERFACE, \
	AUDIO_CS_AC_INTERFACE_SELECTOR_UNIT, \
	_bUnitID, \
	4, \
	_baSourceID1, _baSourceID2, _baSourceID3, _baSourceID4, \
	_bmControls, \
	_iSelector

/* 4.7.2.8 Feature Unit Descriptor */
#define TUD_AUDIO_DESC_FEATURE_UNIT_THREE_CHANNEL_LEN (6+(3+1)*4)
#define TUD_AUDIO_DESC_FEATURE_UNIT_THREE_CHANNEL(_unitid, _srcid, _ctrlch0master, _ctrlch1, _ctrlch2, _ctrlch3, _stridx) \
	TUD_AUDIO_DESC_FEATURE_UNIT_THREE_CHANNEL_LEN, \
	TUSB_DESC_CS_INTERFACE, \
	AUDIO_CS_AC_INTERFACE_FEATURE_UNIT, \
	_unitid, \
	_srcid, \
	U32_TO_U8S_LE(_ctrlch0master), \
	U32_TO_U8S_LE(_ctrlch1), U32_TO_U8S_LE(_ctrlch2), U32_TO_U8S_LE(_ctrlch3), \
	_stridx


#define TUD_AUDIO_DESC_CS_AC_LEN_TOTAL ( \
	TUD_AUDIO_DESC_CLK_SRC_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_FEATURE_UNIT_THREE_CHANNEL_LEN \
	+ TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
	\
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_INPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN \
	+ TUD_AUDIO_DESC_SELECTOR_UNIT_4_LEN \
	+ TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
	+ TUD_AUDIO_DESC_OUTPUT_TERM_LEN \
	)

#define TUD_AUDIO_DESC_TOTAL_LEN ( \
	TUD_AUDIO_DESC_IAD_LEN \
	+ TUD_AUDIO_DESC_STD_AC_LEN \
		+ TUD_AUDIO_DESC_CS_AC_LEN \
			+ TUD_AUDIO_DESC_CS_AC_LEN_TOTAL \
		+ TUD_AUDIO_DESC_STD_AS_INT_LEN \
		+ TUD_AUDIO_DESC_STD_AS_INT_LEN \
	+ TUD_AUDIO_DESC_CS_AS_INT_LEN \
		+ TUD_AUDIO_DESC_TYPE_I_FORMAT_LEN \
		+ TUD_AUDIO_DESC_STD_AS_ISO_EP_LEN \
		+ TUD_AUDIO_DESC_CS_AS_ISO_EP_LEN \
	)


#define MS_OS_20_SET_HEADER_DESCRIPTOR_LEN        (0x0A)
#define MS_OS_20_SUBSET_HEADER_CONFIGURATION_LEN  (0x08)
#define MS_OS_20_SUBSET_HEADER_FUNCTION_LEN       (0x08)
#define MS_OS_20_FEATURE_COMPATIBLE_ID_LEN        (0x14)

#define MS_OS_20_FEATURE_REG_PROPERTY_NAME_LEN    (0x2A)
#define MS_OS_20_FEATURE_REG_PROPERTY_DATA_LEN    (0x50)
#define MS_OS_20_FEATURE_REG_PROPERTY_LEN         (0x0A + MS_OS_20_FEATURE_REG_PROPERTY_NAME_LEN + MS_OS_20_FEATURE_REG_PROPERTY_DATA_LEN)

#define MS_OS_20_SUBSET_HEADER_FUNCTION_LEN_TOTAL ( \
	MS_OS_20_SUBSET_HEADER_FUNCTION_LEN \
	+ MS_OS_20_FEATURE_COMPATIBLE_ID_LEN \
	+ MS_OS_20_FEATURE_REG_PROPERTY_LEN \
)

#define MS_OS_20_SUBSET_HEADER_CONFIGURATION_LEN_TOTAL ( \
	MS_OS_20_SUBSET_HEADER_CONFIGURATION_LEN \
	+ MS_OS_20_SUBSET_HEADER_FUNCTION_LEN_TOTAL \
)

#define MS_OS_20_SET_HEADER_DESCRIPTOR_LEN_TOTAL ( \
	MS_OS_20_SET_HEADER_DESCRIPTOR_LEN \
	+ MS_OS_20_SUBSET_HEADER_CONFIGURATION_LEN_TOTAL \
)

#define MS_OS_20_DESC_LEN        (MS_OS_20_SET_HEADER_DESCRIPTOR_LEN_TOTAL)
#define BOS_TOTAL_LEN            (TUD_BOS_DESC_LEN + TUD_BOS_MICROSOFT_OS_DESC_LEN)
#define VENDOR_REQUEST_MICROSOFT (0x01)

#endif
